spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url:  jdbc:postgresql://13.127.205.125:5432/ram
    username: postgres
    password: rbd@6321P

server:
  port: 80

management:
  endpoints:
    web:
      exposure:
        include: "*"
    shutdown:
      enabled: true