spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url:  jdbc:postgresql://13.127.205.125:5432/ram
    username: postgres
    password: rbd@6321P

server:
  port: 80

management:
  endpoints:
    web:
      exposure:
        include: "*"
    shutdown:
      enabled: true

keycloak:
  realm: insobu-dev
  auth-server-url: https://dev.insobu.padmini.systems/auth
  ssl-required: external
  resource: insobu-api
  credentials:
    secret: 628989a2-b08c-4daa-b82d-3ce9908c09f1
  use-resource-role-mappings: true
  bearer-only: true